# Generated by Django 5.0.2 on 2024-02-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('ido', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tény',
                'verbose_name_plural': 'Tények',
            },
        ),
    ]
